# Site wide configuration
title:  "The Human Performance Modeling Technical Group (HPMTG)"
description:  "This is the website for the HFES HPMTG."
logo:  # 120x120 px default image used for Twitter summary card
teaser:  # 400x250 px default teaser image used in image archive grid
locale:  en
url:  https://hpmtg.github.io
baseurl:  /hpmtg.github.io
feed: 
  path: atom.xml

# Jekyll configuration, per the Github Pages site
lsi: false
safe: true
load_paths:
  - _sass
  - node_modules
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  # - jekyll-menus
# header_pages:
 # - about.md 

# Site owner
owner:
  name: Adam M. Houser, Ph.D.
  email: adamhous@buffalo.edu
  twitter:
  google:
  ad-client:
  ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:
  links:
    - label: "Webmaster Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:adamhous@buffalo.edu"  

include:
  - .htaccess
  - _data
  - _includes
  - _layouts
  - _pages
  - _sass
  - _site
  - _templates

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false