# Skinny Bones Gemfile
source "https://rubygems.org"

gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"

gem "webrick", "~> 1.7"

gem "github-pages", "~> 227", group: :jekyll_plugins
